name: build-and-release-addon
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    tags: ["v*"]

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gettext
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Extract Changelog
        run: |
          import itertools
          import re
          pattern = "^## v\d\.\d\.\d"
          with open("changelog.md", "r", encoding="UTF-8") as f:
            text = f.read()
          matches = tuple(itertools.islice(re.finditer(pattern, text, re.MULTILINE | re.IGNORECASE), 2))
          string = text[matches[0].start():matches[1].start() - 1].strip() + "\n"
          with open("release_description.md", "w", encoding="UTF-8") as f:
            f.write(string)
        shell: python
      - name: Build add-on
        run: |
          uv run scons
          uv run scons pot
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release create "${{ github.ref_name }}" \
          "*.nvda-addon *.pot" \
          --title "${{ github.ref_name }}" \
          --notes-file "release_description.md" \
          --verify-tag
